name: Update Organization Contributors with Total Commits

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st of each month
  workflow_dispatch: # Allows manual triggering

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Fetch all repositories in the organization
        run: |
          echo "Fetching all repositories..."
          gh repo list SigmoidAI --limit 100 --json name -q '.[].name' > repos.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch contributors and commit counts, then aggregate
        run: |
          declare -A contributor_commits

          while IFS= read -r repo; do
            echo "Processing repository: $repo"
            gh api repos/SigmoidAI/$repo/contributors --paginate --jq '.[] | {login: .login, commits: .contributions}' > tmp_contributors.json

            while IFS= read -r line; do
              contributor=$(echo "$line" | awk '{print $1}')
              commits=$(echo "$line" | awk '{print $2}' | tr -d '()')

              if [[ -n "$contributor" && -n "$commits" ]]; then
                contributor_commits[$contributor]=$(( ${contributor_commits[$contributor]:-0} + commits ))
              fi
            done < <(jq -r '.login + " " + (.commits | tostring)' tmp_contributors.json)
          done < repos.txt

          echo "# Organization Contributors" > CONTRIBUTORS.md
          echo "This list is auto-generated and sorted by total contributions across all repositories." >> CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md

          for contributor in "${!contributor_commits[@]}"; do
            echo "$contributor ${contributor_commits[$contributor]}" >> sorted_contributors.txt
          done

          sort -k2 -nr sorted_contributors.txt | while read -r contributor total_commits; do
            echo "- @$contributor: $total_commits commits" >> CONTRIBUTORS.md
          done

          rm -f sorted_contributors.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add CONTRIBUTORS.md
          git commit -m "Updated contributors list sorted by total contributions" || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
