name: Daily PR Leaderboard Update

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Permission to write repository contents (for committing the leaderboard)

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run PR leaderboard script
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: python scripts/pr_leaderboard.py
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./profile/README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update PR leaderboard in README"
          git push 
